-- Execute no SQL Editor do Supabase: https://supabase.com/dashboard
--
-- Uma tabela so. O curriculo, a carta e o dossie sao enviados no Telegram e
-- descartados: guardar arquivo no banco nao acrescenta nada aqui.

CREATE TABLE IF NOT EXISTS public.vagas_processadas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo_vaga     TEXT NOT NULL,
    empresa         TEXT,
    link_vaga       TEXT,
    fonte           TEXT,
    modalidade      TEXT,
    localizacao     TEXT,
    match_score     INT,
    justificativa   TEXT,
    resumo_adaptado TEXT,
    status          TEXT DEFAULT 'notificada',
    provider_ia     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- O dedupe consulta por link e por titulo+empresa: sem indice, cada rodada faz
-- varredura completa da tabela.
CREATE UNIQUE INDEX IF NOT EXISTS vagas_processadas_link_uidx
    ON public.vagas_processadas (link_vaga)
    WHERE link_vaga IS NOT NULL;

CREATE INDEX IF NOT EXISTS vagas_processadas_titulo_empresa_idx
    ON public.vagas_processadas (lower(titulo_vaga), lower(empresa));

-- Seguranca: banco de uso pessoal, acessado so pela chave de servico.
ALTER TABLE public.vagas_processadas ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vagas_processadas FROM anon;
GRANT ALL ON public.vagas_processadas TO service_role;
